#!/bin/bash

NAME=$1

if [[ -z $NAME ]]; then
    echo "No task given"
    exit 1
fi

BUILD_DIR="tmp-build"

[[ ! -d $BUILD_DIR ]] && mkdir $BUILD_DIR
rm -rf $BUILD_DIR/* ./*.jar

export HADOOP_CLASSPATH="$JAVA_HOME/lib/tools.jar:`pwd`"
export CLASSPATH="`$HADOOP_INSTALL/bin/hadoop classpath`:`pwd`"
export -p | grep CLASS

$HADOOP_INSTALL/bin/hadoop com.sun.tools.javac.Main task/${NAME}.java common/*.java common/mr/*.java -d $BUILD_DIR -Xlint:unchecked
jar -cvf ${NAME}.jar -C $BUILD_DIR ./
